# Generated by Django 2.1.7 on 2019-09-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
